from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'calculadora_icone_32x32.jpg'

# Sizing
BIG_FONT_SIZE = 40
MID_FONT_SIZE = 24
LOW_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUN_WIDTH = 500

# Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'
